env:
  browser: true
  es6: true
  node: true
  webextensions: true

extends:
  - eslint:recommended
  - plugin:mozilla/recommended

plugins:
  - mozilla

globals:
  Metrics: true
  SpeakToMe: true
  TestPilotGA: true
  bodymovin: true

rules:
  eqeqeq: error
  no-console: off # TODO: Set back to "warn"
  no-unused-vars: [error, {vars: all, args: none, ignoreRestSiblings: false}]
  no-var: error
  no-warning-comments: off
  prefer-const: error
  mozilla/no-import-into-var-and-global: off
  prettier/prettier: off
