[timer.set]
description = "Set timer"
match = """
    (set | open | show | start | create | make |) (a |) (timer | countdown) (for |) [time]
    (set | start | create | make |) (for |) (alarm ) [time] (from now |)
    [time] minute{s} (timer |) (from now |) [suffixTime=minutes]
    [time] hour{s} (timer |) (from now |)   [suffixTime=hour]
    [time] second{s} (timer |) (from now |) [suffixTime=seconds]

"""

[[timer.set.example]]
phrase = "Set timer for 2 hours and 5 minutes"

[[timer.set.example]]
phrase = "Set alarm 2 minutes from now"

[[timer.set.example]]
phrase = "5 minutes"

[[timer.set.example]]
phrase = "30 seconds"

[[timer.set.example]]
phrase = "1 hour"

[[timer.set.example]]
phrase = "Set alarm for 1 hour from now"
test = true

[timer.set.followup]
match = """
    reset (timer |)
"""

[timer.close]
description = "Close timer"
match = """
    (close | exit | stop | cancel | end) (this | the | current |) (timer | countdown)
"""

[[timer.close.example]]
phrase = "close timer"
test = true

[timer.reset]
description = "Reset timer"
match = """
    (reset | restart) (this | the | current |) (timer | countdown |)
"""

[[timer.reset.example]]
phrase = "reset"

[[timer.reset.example]]
phrase = "reset timer"
test = true

[timer.pause]
description = "Pause timer"
match = """
    pause (this | the | current |) (timer | countdown)
"""

[[timer.pause.example]]
phrase = "pause timer"
test = true

[timer.unpause]
description = "Unpause timer"
match = """
    (unpause | resume | start) (this | the | current |) (timer | countdown)
"""

[[timer.unpause.example]]
phrase = "unpause timer"
test = true
