[window.switch]
description = "Switch the current window"
match = """
  (switch | activate | focus) (the | to |) next window [direction=next]
  (switch | activate | focus) (the | to |) (previous | last) window [direction=back]
"""

[window.quitApplication]
description = "Close Firefox"
match = """
  (close | quit | exit | shutdown) firefox
"""
