[window.switch]
description = "Switch the current window"
match = """
  (switch | activate | focus) (the | to |) next window [direction=next]
  (switch | activate | focus) (the | to |) (previous | last) window [direction=back]
"""

[window.downloads]
description = "Open downloads"
match = """
  (show | open |) downloads (menu |)
"""
