[nicknames.combined]
description = "An intent that is only used as a memory"
match = """
# Nothing to match
"""

[nicknames.name]
description = "Names an intent"
match = """
  (name | nickname | shortcut | call) (that | it | last) [name]
  give (that |) (the |) (name | nickname | shortcut) [name]
  give (the |) (name | nickname | shortcut) [name] to (that | it | last)
"""

[[nicknames.name.example]]
phrase = "Name that calendar"

[nicknames.nameLast]
description = "Combines a few intents into a name"
match = """
  (name | nickname | call | shortcut) last [number:smallNumber] [name]
  give (the |) last [number:smallNumber] (the |) (name | nickname | shortcut) [name]
  give (the |) (name | nickname | shortcut) [name] to (the |) last [number:smallNumber]
"""

[[nicknames.nameLast.example]]
phrase = "Name last three goodmorning"

[nicknames.remove]
description = "Removes a named intent"
match = """
  (remove | delete) (the|) (name | nickname | shortcut) (called |) [name]
"""

[[nicknames.remove.example]]
phrase = "Remove name calendar"

[nicknames.namePage]
description = "Name a page"
match = """
 name (this |) (this | page | tab) [name]
 give (the |) name [name] to (this |) (page | tab)
"""

[[nicknames.namePage.example]]
phrase = "name this page news"

[[nicknames.namePage.example]]
phrase = "give the name news to this tab"
test = true

[nicknames.removePageName]
description = "Remove a page name"
match = """
  (remove | delete) (the |) (page | tab) (name | nickname | shortcut |) (called |) [name] 
  (remove | delete) (the | this |) (page | tab) name
"""

[[nicknames.removePageName.example]]
phrase = "delete the page called news"

[[nicknames.removePageName.example]]
phrase = "remove this tab name"