[linguee.say]
description = "Say the word on linguee"
match = """
(say | speak | utter | ) [ query ] (on | in | )linguee
"""

[[linguee.say.example]]
phrase = "say fox on linguee"
test = true
expectParameters = {service = "linguee"}
expectSlots = {query = "query"}