[read.read]
description = "Narrate the given page. This puts the page into Reader Mode (failing if it can't) and starts narration"
match = """
  (can you |) read (me | ) (this | the |) (out content |) (article | articles | text |) (on this| )(tab | page |) (for me | to me |) (aloud |)
  read (me |) [query] (for me | to me |) (aloud |)
"""

[[read.read.example]]
phrase = "Read this page"

[[read.read.example]]
phrase = "Read out content to me"
test = true

[read.stopRead]
description = "Stop reading/narrating the current tab"
match = """
  stop reading (this |) (tab | page |) (to me | for me |)
"""

[[read.stopRead.example]]
phrase = "Stop reading"

[read.forwardRead]
description = "Forward reading/narrating"
match = """
  forward (this |) (tab | page | paragraph) (to me | for me |)
"""

[[read.forwardRead.example]]
phrase = "forward paragraph"

[[read.forwardRead.example]]
phrase = "forward this page"

[read.backwardRead]
description = "Backward reading/narrating"
match = """
  backward (this |) (tab | page |) (to me | for me |)
"""

[[read.backwardRead.example]]
phrase = "backward"

[[read.backwardRead.example]]
phrase = "backward this"
